# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [main, release-uswds-*]
  pull_request:
    branches: [main, release-uswds-*]
jobs:
  # First Job - ensures app builds
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci
  # Second job - runs testing and linting
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Prettier
        run: npm run prettier:write
      - name: Lint
        run: npm run lint
      - name: Unit test
        run: npm test
      - name: Check for changes
        run: |
          if [[ `git status --porcelain` ]]; then
            # Changes
            echo "changes_exist=true" >> $GITHUB_ENV
          else
            # No changes
            echo "changes_exist=false" >> $GITHUB_ENV
          fi
      - name: Commit changes
        if: ${{ env.changes_exist == true }}
        run: |
          echo "env.changes_exist:"
          echo ${{ env.changes_exist }}
          git config user.name $USERNAME
          git config user.email $EMAIL
          git add .
          git commit -m "Github actions ci changes"
          git remote add origin https://$PAT:x-oauth-basic@github.com/${{ github.event.repository.name }}
          git push origin -f

